using Pgvector;

namespace PlanIt.Api.Domain.Entities;

// One row per WorkItem, generated by the in-process ONNX runtime (all-MiniLM-L6-v2, 384-dim).
// Separate table from WorkItemEmbeddingPython: different model, different vector space, cosine
// similarity across the two is meaningless (planit-similar-tasks-semantic-embeddings.md).
public class WorkItemEmbeddingOnnx
{
    public Guid WorkItemId { get; set; }
    public Vector Vector { get; set; } = null!;

    // Title + " " + Description at the time this vector was computed — lets the background
    // sweep detect drift without re-embedding on every scan.
    public string SourceText { get; set; } = string.Empty;
    public DateTimeOffset ComputedAt { get; set; }

    public WorkItem WorkItem { get; set; } = null!;
}
